services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173"
      - SECRET_KEY=changethis123
      - PROJECT_NAME=Full Stack FastAPI Application
      - FIRST_SUPERUSER=adaeze@gmail.com
      - FIRST_SUPERUSER_PASSWORD=adababy123
      - USERS_OPEN_REGISTRATION=True
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app_db
      - POSTGRES_USER=adaeze
      - POSTGRES_PASSWORD=1234

    command: /bin/bash -c "poetry run sh ./prestart.sh && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: adaeze
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '8090:81'
      - '3001:3000'
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
      - ./conf_files:/conf_files
      - ./entrypoint.sh:/entrypoint.sh

volumes:
  db_data:

 
